import Head from 'next/head'
import { GetStaticProps } from 'next'
import styles from './index.module.scss'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
          <p className={styles.aaa}>这个是得意黑字体吗？ This is a deyihei ？？？</p>
          <p className={styles.bbb}>这个是得意黑字体吗？ This is a deyihei ？？？</p>
        </h1>
      </main>
    </div>
  )
}
export const getStaticProps: GetStaticProps = async context => {
  // console.log(process.env.AAAA, '哈哈哈')

  return {
    // notFound: true,
    props: {
      text: 'look this will log where',
      context: JSON.stringify(context),
    }, // will be passed to the page component as props
  }
}
